<!DOCTYPE html>
<html>
    <head>
        <meta charset=”utf-8” />
        <title >Operating systems</title>
        <link href="styles.css" rel="stylesheet" type="text/css"/>
    </head>
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <!--outer "div"-->
    <body style="background-color:#6699ff;">
    <center>
    
    <!--<header> <h1><center> Linux</center> </h1></header>-->
    <h1><span class="rainbow">Linux</h1>
    <div>
    <!--<nav> <hr width="50%"/>-->
    <!--<a href="index.php"> Home </a>-->
    <!-- <a href="windows.php"> Windows </a>-->
    <!-- <a href="mac.php"> Mac OS X</a>-->
    <!-- <a href="linux.php"> <u>Linux</u></a>-->
    <!--</nav>-->
        <ul>
  <li><a href="index.php">Home</a></li>
  <li><a href="windows.php">Windows</a></li>
  <li><a href="mac.php">Mac OS X</a></li>
  <li><a href="linux.php">Linux</a></li>
  <!--<li style="float:right"><a class="active" href="#about">About</a></li>-->
</ul>
    
    <div id="justify">
        <br> <br>
        <img src="img/linux.png"   alt="linux logo" width="200" > <br>
        <b> Linux </b> is the most famous open-source operating system. It works just like other operating system but presents the benefit of being open-sourced.
        Thats means that anybody can see the code, edit it. Everybody can contribute to the improvement of Linux.
        Almost two-third of the webpages are generated by servers using Linux.
        Linux is a complete and free operating system, which can be used in place of commercialized operating systems, such as Windows, from Microsoft. It is accompanied by many complementary free software, offering a complete system to users. The system can be used on servers (LAN or web servers), on PCs or on smartphones. Linux is available in several versions, freely downloadable on the net, and named "distributions", such as Debian or Ubuntu.
    </div>
    
    
    
    
    
    
    <p style="clear: both;">    
<hr>
<div>
    <h4> Sources</h4>
    <link>
    <a href="https://opensource.com/resources/linux">opensource.com </a>
    </link>
</div>
</p>
    <footer>
            <hr>
            Alexandre MICHAUDET <br>
            CST336 : Internet Programming. 2017&copy; Jason Henderson <br/>
            <strong>Disclaimer:</strong> This webpage is used for academic purposes only.<br/>
            
        </footer>
